server:
  port: 8080

spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://auth-db:5432/auth-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: iamroot


logging:
  level:
    org:
      springframework:
        security: TRACE